# Generated by Django 4.2.19 on 2025-02-20 10:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="core.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecificCompetences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "division",
                    models.CharField(
                        blank=True,
                        help_text="Suggestion: Enter A for 1º ESO A, B for 1º ESO B. Leave blank if no divisions exist.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "specific_competences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="List of specific competence UUIDs",
                        size=None,
                    ),
                ),
                (
                    "basic_knowledge",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="List of basic knowledge UUIDs",
                        size=None,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="core.school",
                    ),
                ),
                (
                    "teaching_staff",
                    models.ManyToManyField(
                        blank=True, related_name="subjects", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="core.year",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "default_years",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="core.year"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schools",
                to="core.schooltype",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="teaching_staff",
            field=models.ManyToManyField(
                blank=True, related_name="schools", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="years",
            field=models.ManyToManyField(blank=True, related_name="+", to="core.year"),
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                (
                    "specific_competences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="List of specific competence UUIDs",
                        size=None,
                    ),
                ),
                (
                    "basic_knowledge",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="List of basic knowledge UUIDs",
                        size=None,
                    ),
                ),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="List of content UUIDs",
                        size=None,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="core.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="core.subject",
                    ),
                ),
                (
                    "teaching_staff",
                    models.ManyToManyField(
                        blank=True, related_name="modules", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="core.year",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningSituation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                (
                    "specific_competences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="List of specific competence UUIDs",
                        size=None,
                    ),
                ),
                (
                    "basic_knowledge",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        help_text="List of basic knowledge UUIDs",
                        size=None,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_situations",
                        to="core.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_situations",
                        to="core.subject",
                    ),
                ),
                (
                    "teaching_staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_situations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_situations",
                        to="core.year",
                    ),
                ),
            ],
        ),
    ]
