# Generated by Django 4.2.19 on 2025-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
