# Generated by Django 4.2.19 on 2025-02-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_region_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningsituation",
            name="basic_knowledge",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="basic_knowledge",
        ),
        migrations.AddField(
            model_name="learningsituation",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_situations",
                to="core.region",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="core.region",
            ),
        ),
        migrations.RemoveField(
            model_name="learningsituation",
            name="specific_competences",
        ),
        migrations.AlterField(
            model_name="learningsituation",
            name="year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_situations",
                to="core.year",
            ),
        ),
        migrations.RemoveField(
            model_name="subject",
            name="specific_competences",
        ),
        migrations.AlterField(
            model_name="subject",
            name="year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="core.year",
            ),
        ),
        migrations.AddField(
            model_name="learningsituation",
            name="specific_competences",
            field=models.ManyToManyField(
                blank=True,
                related_name="learning_situations",
                to="core.specificcompetences",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="specific_competences",
            field=models.ManyToManyField(
                blank=True, related_name="subjects", to="core.specificcompetences"
            ),
        ),
    ]
