# Generated by Django 4.2.19 on 2025-02-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_learningsituation_basic_knowledge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specificcompetences",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specific_competences",
                to="core.region",
            ),
        ),
    ]
