# Generated by Django 4.2.19 on 2025-02-20 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_specificcompetences_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schools",
                to="core.region",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="school_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schools",
                to="core.schooltype",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="teaching_staff",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="schools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
