# Generated by Django 4.2.19 on 2025-02-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_school_address_alter_school_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="years",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="core.year"
            ),
        ),
    ]
