# Generated by Django 4.2.19 on 2025-02-20 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_school_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="teaching_staff",
            field=models.ManyToManyField(
                blank=True, related_name="schools", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="years",
            field=models.ManyToManyField(blank=True, related_name="+", to="core.year"),
        ),
    ]
