# Generated by Django 4.2.19 on 2025-03-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_school_teaching_staff_alter_school_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningsituation",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="learningsituation",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
