# Generated by Django 4.2.19 on 2025-03-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_learningsituation_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningsituation",
            name="modules",
            field=models.ManyToManyField(
                blank=True, related_name="learning_situations", to="core.module"
            ),
        ),
    ]
