# Generated by Django 4.2.19 on 2025-03-21 11:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_learningsituation_modules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="basic_knowledge",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                help_text="List of basic knowledge UUIDs",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="content",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                help_text="List of content UUIDs",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="specific_competences",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                help_text="List of specific competence UUIDs",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="teaching_staff",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="modules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
