# Generated by Django 4.2.19 on 2025-03-29 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_schoolcalendar_term_scheduledlearningsituation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit_number",
                    models.IntegerField(
                        help_text="The sequence number of this unit in the plan"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom title for this unit",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "learning_situation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_placements",
                        to="core.learningsituation",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_units",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "unit_number"],
                "unique_together": {("subject", "unit_number")},
            },
        ),
    ]
