# Generated by Django 4.2.19 on 2025-03-30 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "10000_merge_20250330_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="teaching_staff",
            field=models.ManyToManyField(
                blank=True, related_name="modules", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
