# Generated by Django 5.2.2 on 2025-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "10003_module_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="evaluable",
            field=models.BooleanField(
                default=False,
                help_text="Whether this module can be evaluated by the teacher",
            ),
        ),
    ]
