# Generated by Django 4.2.19 on 2025-03-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_planningunit"),
        ("core", "9999_add_subject_year_to_competences"),
    ]

    operations = []
