# Generated by Django 4.2.19 on 2025-03-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "10001_alter_module_teaching_staff"),
        ("core", "9998_add_evaluation_criteria_and_session_length"),
    ]

    operations = []
