# Generated by Django 4.2.19 on 2025-03-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "10002_merge_20250330_2201"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="files",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of file attachments with metadata",
                null=True,
            ),
        ),
    ]
