# Generated by Django 4.2.19 on 2025-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("school", "School"),
                    ("teacher", "Teacher"),
                ],
                default="",
                help_text="Designates the type of user.",
                max_length=20,
            ),
        ),
    ]
